# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = app/db/migrations

# template used to generate migration file names;
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# file.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a companion .py file to be considered as revisions
# in the versions/ directory
# sourceless = false

# version location specification; This defaults
# to app/db/migrations/versions.  When using multiple version
# directories, initial revs will go to the first directory,
# unless overridden by a specific command line flag.
# version_locations = %(here)s/bar:%(here)s/bat:app/db/migrations/versions

# version path separator; used when applying the above variable
# and when writing version files.  Valid values are (comma, whitespace, newline, none)
# version_path_separator = 

# set to 'true' to search source files recursively
# in each "version_locations" directory
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql://chatbot:chatbot123@db:5432/chatbot_db


[post_write_hooks]
# post_write_hooks allows scripts or Python functions to be run
# after generate() is called.  Examples include our favorite-formatting
# scripts like "black" or "ruff".

# render_item is a Python function that can be used
# to customize the rendering of types in the generated
# migration script.
# render_item = app.db.migrations.render_item

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
