"""chatbot-mvp-completion

Revision ID: 124c80897005
Revises: 
Create Date: 2026-07-12 23:13:30.818209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '124c80897005'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Nombre del negocio (ej: 'Salon Belén')"),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Slug para URLs amigables /{slug}/dashboard'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción breve del negocio'),
    sa.Column('active', sa.Boolean(), nullable=True, comment='Negocio activo en el sistema'),
    sa.Column('whatsapp_phone_id', sa.String(length=50), nullable=True, comment='WhatsApp Business Phone ID'),
    sa.Column('whatsapp_business_account_id', sa.String(length=100), nullable=True, comment='WhatsApp Business Account ID'),
    sa.Column('whatsapp_verify_token', sa.String(length=100), nullable=True, comment='Verify token para el webhook de Meta'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='Timezone del negocio'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='Código de moneda para precios'),
    sa.Column('accept_cards', sa.Boolean(), nullable=True, comment='Acepta tarjetas de crédito/débito'),
    sa.Column('accepts_cash', sa.Boolean(), nullable=True, comment='Acepta efectivo'),
    sa.Column('use_whatsapp_templates', sa.Boolean(), nullable=True, comment='Usar templates pagos de Meta para recordatorios (sin restricción 24h)'),
    sa.Column('owner_phone', sa.String(length=50), nullable=True, comment='WhatsApp del dueño para notificaciones de fallo de recordatorio'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_id'), 'business', ['id'], unique=False)
    op.create_index(op.f('ix_business_slug'), 'business', ['slug'], unique=True)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio al que pertenece la FAQ'),
    sa.Column('question', sa.String(length=500), nullable=False, comment='Pregunta frecuente'),
    sa.Column('answer', sa.Text(), nullable=False, comment='Respuesta a la pregunta frecuente'),
    sa.Column('order', sa.Integer(), nullable=True, comment='Orden de visualización (menor primero)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='FAQ activa y visible'),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Categoría (ej: 'precios', 'turnos', 'pagos')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_id'), 'faq', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio de la interacción'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='ID de sesión de WhatsApp asociada'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Puntaje de satisfacción (1 a 5)'),
    sa.Column('comment', sa.String(length=1000), nullable=True, comment='Comentario opcional del cliente'),
    sa.Column('outcome', sa.Enum('turno_exitoso', 'escalado_exitoso', 'abandonado', 'fallback_malicioso', name='feedback_outcome'), nullable=True, comment='Resultado de la interacción'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Momento de la calificación'),
    sa.Column('user_phone', sa.String(length=20), nullable=True, comment='Teléfono del cliente (para guest)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('metric_thresholds',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno'),
    sa.Column('business_id', sa.Integer(), nullable=True, comment='Negocio (NULL = default del sistema)'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='Nombre de la métrica (ej: csat_average)'),
    sa.Column('warning_value', sa.Float(), nullable=False, comment='Valor del umbral warning'),
    sa.Column('critical_value', sa.Float(), nullable=False, comment='Valor del umbral critical'),
    sa.Column('operator', sa.Enum('lt', 'gt', name='threshold_operator'), nullable=True, comment='lt: valor menor que umbral es malo, gt: valor mayor que umbral es malo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_thresholds_id'), 'metric_thresholds', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio propietario del producto'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Nombre del producto'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Slug para URLs amigables'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción detallada del producto'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio de venta al público'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Costo interno para cálculo de márgenes'),
    sa.Column('stock_quantity', sa.Integer(), nullable=True, comment='Cantidad disponible en inventario'),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True, comment='Umbral para alerta de bajo stock'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Producto activo y visible en el catálogo'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL de imagen del producto'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio propietario del servicio'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Nombre del servicio (ej: 'Corte de Cabello')"),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Slug para URLs amigables'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción detallada del servicio'),
    sa.Column('category', sa.Enum('corte', 'coloración', 'tratamiento', 'barba', 'otros', name='service_category'), nullable=False, comment='Categoría principal del servicio'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='Subcategoría opcional'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Precio en la moneda del negocio'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duración estimada en minutos'),
    sa.Column('slots_available_per_day', sa.Integer(), nullable=True, comment='Cantidad de slots disponibles por día'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Servicio activo y visible en el catálogo'),
    sa.Column('requires_stock', sa.Boolean(), nullable=True, comment='Indica si el servicio consume stock de producto'),
    sa.Column('stock_quantity', sa.Integer(), nullable=True, comment='Cantidad disponible en stock'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL de imagen representativa del servicio'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio al que pertenece el usuario'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Nombre completo del usuario'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email para notificaciones y login'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Número de WhatsApp personal'),
    sa.Column('role', sa.Enum('admin', 'operator', 'guest', name='user_role'), nullable=True, comment='admin=todo, operator=chatbot limitado, guest=read-only'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Usuario activo en el sistema'),
    sa.Column('password_hash', sa.String(length=256), nullable=True, comment='Hash de contraseña para login (si aplica)'),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True, comment="Proveedor OAuth usado (ej: 'google')"),
    sa.Column('oauth_id', sa.String(length=100), nullable=True, comment='ID del usuario en el proveedor OAuth'),
    sa.Column('can_manage_appointments', sa.Boolean(), nullable=True, comment='Puede gestionar turnos'),
    sa.Column('can_view_analytics', sa.Boolean(), nullable=True, comment='Puede ver dashboard de métricas'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_id'),
    sa.UniqueConstraint('phone', 'business_id', name='uq_user_phone_business')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio del turno'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ID del usuario si está registrado; NULL para guest'),
    sa.Column('user_phone', sa.String(length=20), nullable=True, comment='Teléfono del cliente (obligatorio para guest)'),
    sa.Column('user_name', sa.String(length=200), nullable=True, comment='Nombre del cliente (obligatorio para guest)'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='Servicio reservado (no se permite borrar servicio con turnos activos)'),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora del turno'),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', name='appointment_status'), nullable=True, comment='Estado actual del turno'),
    sa.Column('no_show_status', sa.Enum('pending', 'confirmed_yes', 'confirmed_no', 'suggested_change', name='no_show_status'), nullable=True, comment='Estado de confirmación del recordatorio T-24hs'),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Momento en que se envió la notificación/recordatorio'),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True, comment='Motivo de cancelación'),
    sa.Column('cancellation_scheduled_date', sa.DateTime(timezone=True), nullable=True, comment='Fecha original del turno cancelado'),
    sa.Column('created_via', sa.Enum('web', 'chatbot', 'api', name='creation_channel'), nullable=True, comment='Canal por el que se creó el turno: web/chatbot/api'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='ID de sesión de WhatsApp asociada'),
    sa.Column('whatsapp_sent_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de envío del mensaje de confirmación'),
    sa.Column('whatsapp_read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de lectura del mensaje'),
    sa.Column('whatsapp_response_type', sa.String(length=50), nullable=True, comment='Tipo de respuesta al recordatorio: confirmó/canceló'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_id'), 'appointment', ['id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio de la sesión'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='ID único de sesión de WhatsApp'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Usuario registrado; NULL para guest'),
    sa.Column('user_phone', sa.String(length=20), nullable=True, comment='Teléfono del cliente'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Inicio de la sesión'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='Fin de la sesión'),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='session_status'), nullable=True, comment='Estado actual de la sesión'),
    sa.Column('n_messages_total', sa.Integer(), nullable=True, comment='Cantidad total de mensajes en la sesión'),
    sa.Column('n_fallbacks', sa.Integer(), nullable=True, comment='Cantidad de fallbacks en la sesión'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_index(op.f('ix_session_session_id'), 'session', ['session_id'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='ID único de la sesión de conversación (FK a session)'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio multi-tenant'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Tipo de evento instrumentado'),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Payload JSON con campos específicos del tipo de evento'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Momento exacto del evento'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Usuario registrado asociado (NULL para guest)'),
    sa.Column('channel', sa.Enum('whatsapp', 'web', name='event_channel'), nullable=True, comment='Canal de origen del evento'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_business_id'), 'event', ['business_id'], unique=False)
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_index(op.f('ix_event_session_id'), 'event', ['session_id'], unique=False)
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno'),
    sa.Column('appointment_id', sa.Integer(), nullable=True, comment='Turno asociado'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio'),
    sa.Column('status', sa.Enum('sent', 'failed', 'outside_window', 'fallback_channel', 'notified_owner', name='reminder_status'), nullable=False, comment='Estado del intento'),
    sa.Column('channel', sa.Enum('whatsapp_text', 'whatsapp_template', 'sms', 'email', name='reminder_channel'), nullable=False, comment='Canal usado para el envío'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Momento del intento'),
    sa.Column('error_reason', sa.Text(), nullable=True, comment='Motivo de falla (si status != sent)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_log_business_id'), 'reminder_log', ['business_id'], unique=False)
    op.create_index(op.f('ix_reminder_log_id'), 'reminder_log', ['id'], unique=False)
    op.create_table('turno_apuesta',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno autoincremental'),
    sa.Column('business_id', sa.Integer(), nullable=False, comment='Negocio de la apuesta'),
    sa.Column('appointment_id', sa.Integer(), nullable=True, comment='Turno relacionado (si aplica)'),
    sa.Column('user_phone', sa.String(length=20), nullable=True, comment='Teléfono del apostador'),
    sa.Column('user_name', sa.String(length=200), nullable=True, comment='Nombre del apostador'),
    sa.Column('scheduled_date', sa.Date(), nullable=False, comment='Fecha sobre la que se apuesta'),
    sa.Column('estimated_turnos', sa.Integer(), nullable=True, comment='Cantidad estimada de turnos por el negocio'),
    sa.Column('apuesta_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Monto apostado'),
    sa.Column('status', sa.Enum('open', 'settled', name='apuesta_status'), nullable=True, comment='open=pendiente de resolución, settled=resuelta'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de última modificación'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turno_apuesta_id'), 'turno_apuesta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turno_apuesta_id'), table_name='turno_apuesta')
    op.drop_table('turno_apuesta')
    op.drop_index(op.f('ix_reminder_log_id'), table_name='reminder_log')
    op.drop_index(op.f('ix_reminder_log_business_id'), table_name='reminder_log')
    op.drop_table('reminder_log')
    op.drop_index(op.f('ix_event_session_id'), table_name='event')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_business_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_session_session_id'), table_name='session')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_appointment_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_metric_thresholds_id'), table_name='metric_thresholds')
    op.drop_table('metric_thresholds')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_faq_id'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_business_slug'), table_name='business')
    op.drop_index(op.f('ix_business_id'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
