"""add_dynamic_modules_to_business

Revision ID: 6134d2f5c746
Revises: 345e91098007
Create Date: 2026-07-31 23:02:16.616171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6134d2f5c746'
down_revision: Union[str, None] = '345e91098007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('enable_services', sa.Boolean(), nullable=True, comment='Módulo de Turnos/Citas'))
    op.add_column('business', sa.Column('enable_products', sa.Boolean(), nullable=True, comment='Módulo de Catálogo'))
    op.add_column('business', sa.Column('enable_faqs', sa.Boolean(), nullable=True, comment='Módulo de Preguntas Frecuentes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'enable_faqs')
    op.drop_column('business', 'enable_products')
    op.drop_column('business', 'enable_services')
    # ### end Alembic commands ###
