"""add_contact_fields_to_business

Revision ID: 8bc4bdb8bd93
Revises: e4696576a1b7
Create Date: 2026-08-01 00:45:08.995411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc4bdb8bd93'
down_revision: Union[str, None] = 'e4696576a1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('address', sa.String(length=255), nullable=True, comment='Dirección física del negocio'))
    op.add_column('business', sa.Column('phone', sa.String(length=50), nullable=True, comment='Teléfono comercial de contacto'))
    op.add_column('business', sa.Column('email', sa.String(length=255), nullable=True, comment='Email comercial de contacto'))
    op.add_column('business', sa.Column('website', sa.String(length=255), nullable=True, comment='Sitio web del negocio'))
    op.add_column('business', sa.Column('instagram', sa.String(length=100), nullable=True, comment='Usuario o link de Instagram'))
    op.add_column('business', sa.Column('facebook', sa.String(length=100), nullable=True, comment='Usuario o link de Facebook'))
    op.alter_column('business', 'contacto',
               existing_type=sa.VARCHAR(length=255),
               comment='Información de contacto resumida',
               existing_comment='Información de contacto',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'contacto',
               existing_type=sa.VARCHAR(length=255),
               comment='Información de contacto',
               existing_comment='Información de contacto resumida',
               existing_nullable=True)
    op.drop_column('business', 'facebook')
    op.drop_column('business', 'instagram')
    op.drop_column('business', 'website')
    op.drop_column('business', 'email')
    op.drop_column('business', 'phone')
    op.drop_column('business', 'address')
    # ### end Alembic commands ###
