"""add_sms_and_email_enabled_to_business

Revision ID: d9d7dbca55b1
Revises: 124c80897005
Create Date: 2026-07-21 19:46:52.010974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9d7dbca55b1'
down_revision: Union[str, None] = '124c80897005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('sms_enabled', sa.Boolean(), nullable=True, comment='SMS habilitado como canal alternativo de recordatorio'))
    op.add_column('business', sa.Column('email_enabled', sa.Boolean(), nullable=True, comment='Email habilitado como canal alternativo de recordatorio'))
    op.create_unique_constraint('uq_business_metric_threshold', 'metric_thresholds', ['business_id', 'metric_name'])
    op.alter_column('reminder_log', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Negocio (NULL si el negocio fue eliminado — preserva audit trail)',
               existing_comment='Negocio')
    op.alter_column('reminder_log', 'status',
               existing_type=postgresql.ENUM('sent', 'failed', 'outside_window', 'fallback_channel', 'notified_owner', name='reminder_status'),
               comment='Estado del intento (pending: creado, aún no procesado)',
               existing_comment='Estado del intento',
               existing_nullable=False)
    op.drop_constraint('reminder_log_business_id_fkey', 'reminder_log', type_='foreignkey')
    op.create_foreign_key(None, 'reminder_log', 'business', ['business_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminder_log', type_='foreignkey')
    op.create_foreign_key('reminder_log_business_id_fkey', 'reminder_log', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reminder_log', 'status',
               existing_type=postgresql.ENUM('sent', 'failed', 'outside_window', 'fallback_channel', 'notified_owner', name='reminder_status'),
               comment='Estado del intento',
               existing_comment='Estado del intento (pending: creado, aún no procesado)',
               existing_nullable=False)
    op.alter_column('reminder_log', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Negocio',
               existing_comment='Negocio (NULL si el negocio fue eliminado — preserva audit trail)')
    op.drop_constraint('uq_business_metric_threshold', 'metric_thresholds', type_='unique')
    op.drop_column('business', 'email_enabled')
    op.drop_column('business', 'sms_enabled')
    # ### end Alembic commands ###
