"""add_category_to_business

Revision ID: e4696576a1b7
Revises: 6134d2f5c746
Create Date: 2026-07-31 23:42:06.577098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4696576a1b7'
down_revision: Union[str, None] = '6134d2f5c746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('category', sa.String(length=50), nullable=True, comment='Macro-categoría del negocio (salud, belleza, retail, etc.)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'category')
    # ### end Alembic commands ###
